feat: docker optimization

diff --git a/Dockerfile.migrate b/Dockerfile.migrate
--- a/Dockerfile.migrate
+++ b/Dockerfile.migrate
@@ -1,18 +1,18 @@
-FROM python:3.12-slim
+FROM python:3.12-slim-trixie
 
 WORKDIR /app
 
-COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
+COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
+
 COPY pyproject.toml uv.lock ./
 
 RUN uv sync --frozen --no-dev --no-install-project --no-editable
 
-COPY /src/ ./src/
-COPY /migration/ ./migration/
-COPY alembic.ini ./alembic.ini
+COPY src/ ./src/
+COPY migration/ ./migration/
+COPY alembic.ini ./
 
-RUN if [ ! -d "/app/migration" ]; then echo "migration folder not found!" && exit 1; fi
-RUN if [ ! -f "/app/alembic.ini" ]; then echo "alembic.ini not found!" && exit 1; fi
-
+RUN test -d /app/migration && test -f /app/alembic.ini || \
+    (echo "❌ Migration files missing!" && exit 1)
 
 CMD ["uv", "run", "alembic", "upgrade", "head"]
